package tui

const (
	KeyFocusSwitch = "tab"
	KeyDown        = "j"
	KeyUp          = "k"
	KeySelect      = "enter"
	KeyAdd         = "a"
	KeyEdit        = "e"
	KeyDelete      = "x"
	KeyProject     = "P"
	KeyToday       = "t"
	KeyDue         = "d"
	KeyComplete    = "c"
	KeyRestore     = "r"
	KeyToggleDone  = "h"
	KeyPurgeTrash  = "X"
	KeyClipAdd     = "p"
	KeyClipAddAI   = "ctrl+a"
	KeyEsc         = "esc"
	KeyBackspace   = "backspace"
	KeyBackspace2  = "ctrl+h"
	KeyQuit        = "q"
	KeyHelp        = "?"
	KeyUndo        = "z"
)
